#!/usr/bin/env python3
"""The notice/short-form reference layer.

Atarashi's own license list carries one full text (plus an optional header) per
license. Real source files do not contain license bodies — they contain short
notices, and a notice sits at ~95% depth of a multi-thousand-token body, so
whole-document scoring never surfaces it. Measured on real headers, the
full-text-only layer scores R@1 ~0.004: it cannot identify them at all. Indexing
the short-form register alongside the bodies is what closes that gap, and it is
why ScanCode works in the wild.

The artifact is generated by ``scripts/build_references.py`` and committed, so
scancode-toolkit is a build-time dependency and never a runtime one. Its keys are
SPDX ids, so it is independent of both ScanCode's and FOSSology's internal naming;
this module maps them onto whatever shortnames the caller's license list uses.

SPDX-License-Identifier: GPL-2.0-only
"""
from __future__ import annotations

import json
from collections.abc import Iterable, Iterator
from pathlib import Path

from atarashi.spdx.resolver import lookup_shortname, shortname_index

DEFAULT_INDEX = Path(__file__).resolve().parents[1] / "data" / "licenses" / "notice_rules.json"

# Shortest reference unit worth indexing. Measured, not assumed — sweeping the floor
# over the 246-query notice regime and the 2,145-query no-signal regime:
#
#   floor  coverage  precision   R@1    no-signal false answers
#     4      65.9%     0.8765   0.5772        1.96%
#     5      65.9%     0.8765   0.5772        1.96%
#     6      62.2%     0.8693   0.5407        1.68%
#     7      60.6%     0.8725   0.5285        1.35%
#     8      59.8%     0.8707   0.5203        1.31%
#
# 5 dominates 4: identical on every measure while dropping ~700 dead units, so no
# four-token rule earns its place. Below 8 the trade is roughly three extra correct
# answers per extra false one, weighted by how often each regime occurs in real code.
MIN_UNIT_TOKENS = 5


def load_notice_units(shortnames: Iterable[str],
                      path: Path | None = None,
                      min_tokens: int = MIN_UNIT_TOKENS) -> Iterator[tuple[str, str, list[str]]]:
    """Yield ``(shortname, text, required_phrases)`` for licenses the caller knows.

    Units keyed to a license absent from ``shortnames`` are dropped: the agent can
    only report licenses in its own list, so indexing the rest costs match time and
    buys nothing.

    Units shorter than ``min_tokens`` are dropped; see ``MIN_UNIT_TOKENS`` for how
    that floor was chosen. Filtering at ``DEFAULT_MIN_RUN`` instead threw away the
    entire short-reference register — 700 of the 1,339 apache-2.0 rules — which is
    the register real files most often carry. Those units are matchable, but only in
    full; ``LicenseMatcher.match`` enforces that. The count is a whitespace split
    rather than the matcher's tokenizer: an approximation, but it avoids tokenizing
    23k units twice at startup.

    Missing or unreadable artifact yields nothing rather than raising, so an agent
    built before the index exists still runs on the full-text layer alone.
    """
    index = shortname_index(shortnames)
    try:
        payload = json.loads(Path(path or DEFAULT_INDEX).read_text())
    except (OSError, ValueError):
        return
    for unit in payload.get("units", ()):
        spdx, text = unit[0], unit[1]
        phrases = unit[2] if len(unit) > 2 else []
        if len(text.split()) < min_tokens:
            continue
        shortname = lookup_shortname(spdx, index)
        if shortname is not None:
            yield shortname, text, phrases
