#!/usr/bin/env python3
"""The notice/short-form reference layer.

Atarashi's own license list carries one full text (plus an optional header) per
license. Real source files do not contain license bodies — they contain short
notices, and a notice sits at ~95% depth of a multi-thousand-token body, so
whole-document scoring never surfaces it. Measured on real headers, the
full-text-only layer scores R@1 ~0.004: it cannot identify them at all. Indexing
the short-form register alongside the bodies is what closes that gap, and it is
why ScanCode works in the wild.

The artifact is generated by ``scripts/build_references.py`` and committed, so
scancode-toolkit is a build-time dependency and never a runtime one. Its keys are
SPDX ids, so it is independent of both ScanCode's and FOSSology's internal naming;
this module maps them onto whatever shortnames the caller's license list uses.

SPDX-License-Identifier: GPL-2.0-only
"""
from __future__ import annotations

import json
from collections.abc import Iterable, Iterator
from pathlib import Path

from atarashi.spdx.resolver import lookup_shortname, shortname_index

DEFAULT_INDEX = Path(__file__).resolve().parents[1] / "data" / "licenses" / "notice_rules.json"

# Shortest reference unit worth indexing. Swept three times; the answer is 5 each
# time, but for different reasons, so both are recorded.
#
# Under the hand-tuned confidence bar, floor 3 cost SPDX-tag precision outright
# (0.9667 -> 0.9585): that bar could not separate a real short declaration from a code
# string, and both are three tokens.
#
# Re-swept with the learned reject option, which sees run length, coverage,
# corroboration and margin, floor 3 looked strictly better *in-sample* — clearing
# ScanCode on all four measures. Held out it does not:
#
#              DEP-5 prec/R@1     SPDX-tag prec/R@1
#   floor 3    0.8771 / 0.8405    0.9609 / 0.9248
#   floor 5    0.8831 / 0.8331    0.9651 / 0.9361
#
# Floor 5 wins on three of four, and floor 3 is behind ScanCode on both SPDX-tag
# measures. The in-sample sweep flattered it because the artifact had been fit on the
# queries it was scored against.
#
# So the short declarations that motivated the change — "licensed under MIT,",
# "License : Apache-2.0" at three tokens — stay unreachable. They are 17 DEP-5 queries,
# and buying them costs more elsewhere than they are worth.
MIN_UNIT_TOKENS = 5


def load_notice_units(shortnames: Iterable[str],
                      path: Path | None = None,
                      min_tokens: int = MIN_UNIT_TOKENS) -> Iterator[tuple[str, str, list[str]]]:
    """Yield ``(shortname, text, required_phrases)`` for licenses the caller knows.

    Units keyed to a license absent from ``shortnames`` are dropped: the agent can
    only report licenses in its own list, so indexing the rest costs match time and
    buys nothing.

    Units shorter than ``min_tokens`` are dropped; see ``MIN_UNIT_TOKENS`` for how
    that floor was chosen. Filtering at ``DEFAULT_MIN_RUN`` instead threw away the
    entire short-reference register — 700 of the 1,339 apache-2.0 rules — which is
    the register real files most often carry. Those units are matchable, but only in
    full; ``LicenseMatcher.match`` enforces that. The count is a whitespace split
    rather than the matcher's tokenizer: an approximation, but it avoids tokenizing
    23k units twice at startup.

    Missing or unreadable artifact yields nothing rather than raising, so an agent
    built before the index exists still runs on the full-text layer alone.
    """
    index = shortname_index(shortnames)
    try:
        payload = json.loads(Path(path or DEFAULT_INDEX).read_text())
    except (OSError, ValueError):
        return
    for unit in payload.get("units", ()):
        spdx, text = unit[0], unit[1]
        phrases = unit[2] if len(unit) > 2 else []
        if len(text.split()) < min_tokens:
            continue
        shortname = lookup_shortname(spdx, index)
        if shortname is not None:
            yield shortname, text, phrases
