# SPDX-FileCopyrightText: 2022 Gaurav Mishra <mishra.gaurav@siemens.com>
# SPDX-FileCopyrightText: 2025 Kaushlendra Pratap Singh <kaushlendra-pratap.singh@siemens.com>
# SPDX-License-Identifier: GPL-2.0

name: Build and test packages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --requirement requirements.txt

      - name: Build and install
        run: |
          python3 setup.py build
          python3 -m pip install .

      - name: Test
        run: |
          atarashi -h
          atarashi -a wordFrequencySimilarity ./atarashi/atarashii.py
          atarashi -a DLD ./atarashi/atarashii.py
          atarashi -a tfidf -s ScoreSim ./atarashi/atarashii.py
          atarashi -a tfidf -s CosineSim ./atarashi/atarashii.py
          atarashi -a Ngram -s CosineSim ./atarashi/atarashii.py
          atarashi -a Ngram -s DiceSim ./atarashi/atarashii.py
          atarashi -a Ngram -s BigramCosineSim ./atarashi/atarashii.py
          atarashi -a Ngram -s BigramCosineSim ./atarashi/agents
