# SPDX-FileCopyrightText: 2025 Gaurav Mishra <mishra.gaurav@siemens.com>
# SPDX-FileCopyrightText: 2025 Kaushlendra Pratap <kaushlendra-pratap.singh@siemens.com>
# SPDX-License-Identifier: GPL-2.0-only

name: Build and test packages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']

    runs-on: ubuntu-latest
    env:
      PYTHONDONTWRITEBYTECODE: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build dependencies
        run: |
          python3 -m pip install --upgrade pip poetry

      - name: Build and install
        run: |
          poetry install
          poetry run preprocess
          poetry build

      - name: Test
        run: |
          poetry run atarashi -h
          poetry run atarashi -a wordFrequencySimilarity ./atarashi/atarashii.py
          poetry run atarashi -a DLD ./atarashi/atarashii.py
          poetry run atarashi -a tfidf -s ScoreSim ./atarashi/atarashii.py
          poetry run atarashi -a tfidf -s CosineSim ./atarashi/atarashii.py
          poetry run atarashi -a Ngram -s CosineSim ./atarashi/atarashii.py
          poetry run atarashi -a Ngram -s DiceSim ./atarashi/atarashii.py
          poetry run atarashi -a Ngram -s BigramCosineSim ./atarashi/atarashii.py
          poetry run atarashi -a Ngram -s BigramCosineSim ./atarashi/agents
