name: Publish Release Packages

on:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: python3 -m pip install --upgrade poetry

      - name: Build packages
        run: |
          poetry install
          poetry run preprocess
          poetry build

      - name: Upload Packages to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
